server:
    port: 8797
    servlet:
        context-path: /

spring:
    cloud:
      gateway:
          discovery:
              locator:
                  enabled: true
          routes:
              - id: payment_route
                uri: http://localhost:8081
                predicates:
                    - Path=/payment/get/**
              - id: payment_route2
                    uri: http://localhost:8081
                    predicates:
                        - Path=/payment/getAll/**
    application:
        name: HQ_bms_roman
    devtools:
      restart:
          enabled: true #设置开启热部署
          additional-paths: hq_bms_honeycomb/src/main/java #重启目录
#    security:
#        basic:
#          enable: true
#        user:
#            name: belink
#            password: byd123
#logging:
#    config: classpath:logback.xml
#    level:
#        com.hq.bms: trace
#        root: warn
# 配置了公钥和私钥的位置
#rsa:
#    key:
#        pubKeyPath: D:\Belink\auth_key\id_key_rsa.pub
#        priKeyPath: D:\Belink\auth_key\id_key_rsa

###服务注册到eureka注册中心的地址
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8796/eureka
        ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
        ###是否需要从eureka上检索服务
        register-with-eureka: true
        fetch-registry: true